# **Uploading files & combining data tables**

In [ ]:
# Importing tools
import pandas as pd
import glob
import numpy as np
from google.colab import files

# Upload Crime Data
# Source: https://data.police.uk/data/
uploaded = files.upload()

Saving 2025-03-metropolitan-street.csv to 2025-03-metropolitan-street.csv
Saving 2025-04-metropolitan-street.csv to 2025-04-metropolitan-street.csv
Saving 2025-05-metropolitan-street.csv to 2025-05-metropolitan-street.csv
Saving 2025-06-metropolitan-street.csv to 2025-06-metropolitan-street.csv
Saving 2025-07-metropolitan-street.csv to 2025-07-metropolitan-street.csv
Saving 2025-08-metropolitan-street.csv to 2025-08-metropolitan-street.csv
Saving 2025-09-metropolitan-street.csv to 2025-09-metropolitan-street.csv
Saving 2025-10-metropolitan-street.csv to 2025-10-metropolitan-street.csv
Saving 2025-11-metropolitan-street.csv to 2025-11-metropolitan-street.csv
Saving 2025-12-metropolitan-street.csv to 2025-12-metropolitan-street.csv
Saving 2026-01-metropolitan-street.csv to 2026-01-metropolitan-street.csv
Saving 2026-02-metropolitan-street.csv to 2026-02-metropolitan-street.csv
Saving 2026-03-metropolitan-street.csv to 2026-03-metropolitan-street.csv
Saving 2026-04-metropolitan-street.csv to 2026-04-metropolitan-street.csv
Saving 2026-05-metropolitan-street.csv to 2026-05-metropolitan-street.csv

In [ ]:
# Checking files
csv_files = list(uploaded.keys())
print(csv_files)

['2025-03-metropolitan-street.csv', '2025-04-metropolitan-street.csv', '2025-05-metropolitan-street.csv', '2025-06-metropolitan-street.csv', '2025-07-metropolitan-street.csv', '2025-08-metropolitan-street.csv', '2025-09-metropolitan-street.csv', '2025-10-metropolitan-street.csv', '2025-11-metropolitan-street.csv', '2025-12-metropolitan-street.csv', '2026-01-metropolitan-street.csv', '2026-02-metropolitan-street.csv', '2026-03-metropolitan-street.csv', '2026-04-metropolitan-street.csv', '2026-05-metropolitan-street.csv']

In [ ]:
# Combining all data into one file
df_list = [pd.read_csv(f) for f in csv_files]
combined_df = pd.concat(df_list, ignore_index=True)
combined_df.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,aa9d008371c86371ad07a7ee37aa0bbc18988fad9c839f...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.841300,51.134961,On or near Lodge Close,E01024017,Ashford 007E,Violence and sexual offences,Unable to prosecute suspect,NaN
1,NaN,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.140194,51.582356,On or near Hatch Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
2,NaN,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
3,88a2f14d227afd35b185e72ffddf624ce3390ce73ad627...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.145722,51.594296,On or near Providence Place,E01000027,Barking and Dagenham 001A,Burglary,Investigation complete; no suspect identified,NaN
4,92b195e28c4e5eaf7534d163af1e0e33e81c7de4d8bf54...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.138830,51.583433,On or near Thatches Grove,E01000027,Barking and Dagenham 001A,Criminal damage and arson,Unable to prosecute suspect,NaN

# Removing Duplicates (Rows with NaN Crime Data are not included)

In [ ]:
# Check total number of rows
print('Total Rows:', combined_df.shape)

Total Rows: (1422271, 12)

In [ ]:
# Check how many rows are duplicates based on Crime ID
print(combined_df['Crime ID'].duplicated().sum())

304281

In [ ]:
# Separate the data into two tables - thoses with a Crime ID and those without one. Rechecking duplicates for data with a Crime ID
has_id = combined_df[combined_df['Crime ID'].notna()].copy()
no_id = combined_df[combined_df['Crime ID'].isna()].copy()
print(has_id['Crime ID'].duplicated().sum())

# Checking table size again
print('Rows with Crime ID:', has_id.shape)
print('Rows with NaN Crime ID:', no_id.shape)

6899
Rows with Crime ID: (1124888, 12)
Rows with NaN Crime ID: (297383, 12)

In [ ]:
# Removing duplicates from the has_id table
combined_df['Month'] = pd.to_datetime(combined_df['Month'], format='%Y-%m')
has_id = has_id.drop_duplicates(subset='Crime ID', keep='last')
print('After deduplicate:', has_id.shape)

After deduplicate: (1117989, 12)

In [ ]:
# Combining tables
combined_df = pd.concat([has_id, no_id], ignore_index=True)
print('Final:', combined_df.shape)

Final: (1415372, 12)

In [ ]:
# Checking the table
combined_df.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,aa9d008371c86371ad07a7ee37aa0bbc18988fad9c839f...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.841300,51.134961,On or near Lodge Close,E01024017,Ashford 007E,Violence and sexual offences,Unable to prosecute suspect,NaN
1,88a2f14d227afd35b185e72ffddf624ce3390ce73ad627...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.145722,51.594296,On or near Providence Place,E01000027,Barking and Dagenham 001A,Burglary,Investigation complete; no suspect identified,NaN
2,92b195e28c4e5eaf7534d163af1e0e33e81c7de4d8bf54...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.138830,51.583433,On or near Thatches Grove,E01000027,Barking and Dagenham 001A,Criminal damage and arson,Unable to prosecute suspect,NaN
3,2a52f3b579cc61f3b1e7f7d4d5ef85a9c6e27c15374277...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.135972,51.588359,On or near Hazel Grove,E01000027,Barking and Dagenham 001A,Drugs,Unable to prosecute suspect,NaN
4,220ac918ba2ece6add0e0267bb0df2f73bbe3f31d7ea8c...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.135924,51.587353,On or near Gibbfield Close,E01000027,Barking and Dagenham 001A,Drugs,Investigation complete; no suspect identified,NaN

# Filtering data based on a 0.5 KM radius from London Office (Using haversine)

In [ ]:
def haversine_dis(lat1, long1, lat2, long2):
  # Covert degrees to radians
  lat1, long1, lat2, long2 = map(np.radians, [lat1, long1, lat2, long2])

  # Differences
  dlat = lat2 - lat1
  dlong = long2 - long1

  # Haversine formuala
  a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlong / 2)**2
  c = 2 * np.arcsin(np.sqrt(a))

  r = 6371 # Radius of Earth in KM
  return r * c

# Lat/Long of London Office
Lon_lat = 51.5068
Lon_long = -0.1310

# Calulating the distance of every crime data point to the London Office. The calculated KM stored into a new column
combined_df['distance_km'] = haversine_dis(
      Lon_lat, Lon_long, combined_df['Latitude'], combined_df['Longitude']
).round(2)

print(combined_df.shape)
combined_df.head()

(1415372, 13)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context,distance_km
0,aa9d008371c86371ad07a7ee37aa0bbc18988fad9c839f...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.841300,51.134961,On or near Lodge Close,E01024017,Ashford 007E,Violence and sexual offences,Unable to prosecute suspect,NaN,79.21
1,88a2f14d227afd35b185e72ffddf624ce3390ce73ad627...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.145722,51.594296,On or near Providence Place,E01000027,Barking and Dagenham 001A,Burglary,Investigation complete; no suspect identified,NaN,21.47
2,92b195e28c4e5eaf7534d163af1e0e33e81c7de4d8bf54...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.138830,51.583433,On or near Thatches Grove,E01000027,Barking and Dagenham 001A,Criminal damage and arson,Unable to prosecute suspect,NaN,20.51
3,2a52f3b579cc61f3b1e7f7d4d5ef85a9c6e27c15374277...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.135972,51.588359,On or near Hazel Grove,E01000027,Barking and Dagenham 001A,Drugs,Unable to prosecute suspect,NaN,20.57
4,220ac918ba2ece6add0e0267bb0df2f73bbe3f31d7ea8c...,2025-03,Metropolitan Police Service,Metropolitan Police Service,0.135924,51.587353,On or near Gibbfield Close,E01000027,Barking and Dagenham 001A,Drugs,Investigation complete; no suspect identified,NaN,20.52

In [ ]:
# Filter all crime outside of a 0.5 KM radius
combined_df = combined_df[combined_df['distance_km'] <= 0.5]

# Check table again
print(combined_df.shape)
combined_df.head()

(9562, 13)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context,distance_km
72037,a0e234efdbbd9e4dbb1f16797f7222f7c462d1788d0ce8...,2025-03,Metropolitan Police Service,Metropolitan Police Service,-0.130120,51.509064,On or near Parking Area,E01004734,Westminster 018A,Bicycle theft,Investigation complete; no suspect identified,NaN,0.26
72038,7acc40fc3503966fe6ba89cec09efb6c2ed529e651a35c...,2025-03,Metropolitan Police Service,Metropolitan Police Service,-0.129192,51.510272,On or near Nightclub,E01004734,Westminster 018A,Bicycle theft,Investigation complete; no suspect identified,NaN,0.41
72039,695e137849cd00aacedda587a41181621824498489483e...,2025-03,Metropolitan Police Service,Metropolitan Police Service,-0.129192,51.510272,On or near Nightclub,E01004734,Westminster 018A,Burglary,Investigation complete; no suspect identified,NaN,0.41
72041,3168bb47d264e4c2ee151d19a46e3a8234dd7d5d18acfe...,2025-03,Metropolitan Police Service,Metropolitan Police Service,-0.131269,51.509514,On or near Parking Area,E01004734,Westminster 018A,Burglary,Investigation complete; no suspect identified,NaN,0.30
72045,95394996f06fd2222045cb5c20553e3ed8681b6934e7b3...,2025-03,Metropolitan Police Service,Metropolitan Police Service,-0.128782,51.509759,On or near Nightclub,E01004734,Westminster 018A,Burglary,Investigation complete; no suspect identified,NaN,0.36

# Export table as a CSV

In [ ]:
out_path = "London_Office_Crime_Data_2025_-_2026.csv"
combined_df.to_csv(out_path, index=False)